name: deploy ASP.Net Core app to an Azure Web App
 
env:
  AZURE_WEBAPP_NAME_DEV: dev-cobra-dotnet-webapp    # set this to the name of your Azure Web App
  AZURE_WEBAPP_NAME_STAGE: stg-cobra-dotnet-webapp    # set this to the name of your Azure Web App
  AZURE_WEBAPP_NAME: cobra-dotnet-webapp    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8'                 # set this to the .NET Core version to use 
on:
  workflow_run:       # For automatic trigger after build
    workflows: ["Build"]
    types:
      - completed
jobs:
  deploytodev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
    runs-on: windows-latest
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          run-id: ${{ github.event.workflow_run.id }}
 
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_DEV }}
          publish-profile: ${{ secrets.devgithubsecretappdeployment }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploytostage:
     permissions:
      contents: none
     runs-on: windows-latest
     needs: deploytodev
     environment:
      name: 'Stage'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
     steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
 
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_STAGE }}
          publish-profile: ${{ secrets.stggithubsecretappdeployment }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploytoproduction:
    permissions:
      contents: none
    runs-on: windows-latest
    needs: deploytostage
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
 
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.githubsecretappdeployment }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
